config/routes.rb
Rails.application.routes.draw do
 
  resources :memos
  resources :arts do 
    resources :favorites, only: [:create, :destroy]
  end
  resources :user_sessions
  resources :users
  
  root 'static_pages#home'
  resources :sitemaps, :only => :index
  get 'sitemap.xml', to: 'sitemaps#index', :format => "xml", :as => :sitemap
  get  'about',  to: 'static_pages#about'
  get  '/help',  to: 'static_pages#help'
  get  'column',  to: 'static_pages#column'

  get 'static_pages/new'
  get  'static_pages/index'
  post 'static_pages/index'

  get  'login'  => 'user_sessions#new',     :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  
  get 'memo',  to: 'memos#index'
  get 'index',  to: 'arts#index'
  get 'new', 	  to: 'arts#new'
  get 'tags/:tag', to: 'arts#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	 # before_action :set_ranking_data
   skip_before_action :require_login

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @@prodcut.save
        format.js #create.js.erbをredeer
      else
        format.js { head :no_content } #エラーの時は返さない
      end
    end
  end

  def new
    respond_to do |format|
      format.json {
        render json: {shape: shape}, status: 200
      }
    end
  end

  def home
  	@tags = Art.tag_counts_on(:tags).order('count DESC')
    @beans = Art.tag_counts_on(:coffeebeans).order('count DESC')
    @arr = Art.pluck(:address)
    @ars = Art.pluck(:storename)
    @ari = Art.pluck(:id)
    @memos = Memo.all
    if params[:tag]
    @art = Art.tagged_with(params[:tag])
    @art = Art.tagged_with(params[:coffeebean])
  else
    @art = Art.all.reverse
  end
  end

  def set_ranking_data
    ids = REDIS.zrevrangebyscore "arts/", "+inf", 0, limit: [0, 3]
    @ranks = Art.where(id: ids).sort_by{ |art| ids.index(art.id.to_s) }
  end

  def about
  end

  def column
    @memos = Memo.all
  end

  def help
  end

  private

  def shape
    ['✊', '✌️', '✋'].sample
  end
end

app/views/static_pages/_bigtitle.html.erb
<%= link_to(@art.last) do %>
<div class="row expanded collapse">
  <div class="column">
    <div class="large-article-header" style="background-image:url(<%= @art.first.mimages[0].url %>);">
      <div class="large-article-header-content">
        <div class="center-container">
          <div class="article-title">
            <h1><%= @art.first.storename %></h1>
          </div>
          <div class="article-details">
          <div style="color:white; position: center;">
            <p><%= @art.first.created_at.strftime("%Y年%m月%d日") %></p>
      	    </div>
            <div class="article-comments">
              <a href="#"><i class="fa fa-comment" aria-hidden="true"><%= @art.first.area %></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/static_pages/_orbit.html.erb
<div class="orbit" role="region" aria-label="Favorite Text Ever" data-orbit>
  <ul class="orbit-container">
    <button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
    <button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
    <li class="is-active orbit-slide">
      <div class="docs-example-orbit-slide">
        <p><strong>This is dodgerblue.</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </li>
    <li class="orbit-slide">
      <div class="docs-example-orbit-slide">
        <p><strong>This is rebeccapurple.</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </li>
    <li class="orbit-slide">
      <div class="docs-example-orbit-slide">
        <p><strong>This is darkgoldenrod.</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </li>
    <li class="orbit-slide">
      <div class="docs-example-orbit-slide">
        <p><strong>This is lightseagreen.</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </li>
  </ul>
  <nav class="orbit-bullets">
    <button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
    <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
    <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
    <button data-slide="3"><span class="show-for-sr">Fourth slide details.</span></button>
  </nav>
</div>

app/views/static_pages/about.html.erb
<% set_meta_tags title: 'About', description: 'COFFEESEEKERについて'  %>
</br>
<div class="cell"><h2 class="maint">About</h2></div>
<div class="cell">
<div class="text-left"><%= markdown("#### *Coffee Seekerとは？*
----
　Coffee Seekerはおいしいコーヒー・おしゃれなカフェを探し求める人のためのサイトです。世界中のカフェが提供するスペシャリティコーヒーを中心に紹介していき、一人でも多くの人がコーヒーの魅力に気づき、自分好みのコーヒー豆を見つけるきっかけになればうれしいです。また、コーヒーに関する豆知識もコラム形式でご紹介していきますので、併せてお楽しみ下さい。  
<br>
#### *スペシャリティーコーヒーとは？*
----
　スペシャリティーコーヒーは文字通りコーヒーの中でも、特別なコーヒーの総称であり、トレーサビリティ（生産農地・生産者・流通経路などが見える化できること）が確立されたものやコーヒーそもそもの味、香味が良いものを指します。
シングルオリジン（ブレンドされていないコーヒー豆）を使用し、コーヒー豆毎に際立った特徴を持っています。
<br>
#### *サイトの使い方*
----
**1.　おしゃれなカフェやおいしいコーヒーを飲みたい人**

　エリア別・コーヒー豆別に記事分けしているので、お近くの地域や旅先でのカフェを事前に確認してみて下さい。

**2.　お気に入りのカフェをブックマークしたい人**

　ユーザー登録をして、記事にあるハートマークをクリックしてみてください。自分のお気に入りのカフェを一覧で確認することができ、誰かとシェアしたりリマインド機能にもなります。
*ゆくゆくはニュースフィードで最新情報の取得やクーポン機能などを増やすようにしていきます。

**3.　コーヒーについて勉強したい人**

　コラムをご覧ください。コーヒーの種類・豆の種類・抽出方法などの基礎知識から、世界中のコーヒー情報をまとめて記事にしていきます。") %></div>
</div>

app/views/static_pages/column.html.erb
<% set_meta_tags title: 'Column', description: 'カフェ・コーヒーのコラムについて'  %>
</br>
<div class="cell"><h2 class="maint">Column</h2></div>
 <% @memos.each do |memo| %>
<div class="media-object">
  <div class="media-object-section">
  <div class="thumbnail">
  <%= image_tag memo.images.url, :size => "200x200" %>
    </div>
     </div>
   <div class="media-object-section linktoart">
    <%= link_to memo_path(memo) do %>
    <h3><strong><%= memo.title %></strong></h3>
    <% end %>
    <p><%= memo.shortcontent %></p>
  </div>
</div>
  <% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="grid-x grid-margin-x">
<div class="cell"><%= render 'bigtitle' %></div>
<div class="cell small-12 medium-9 large-9">
<div class="cell small-title">
<h5 class="readmore clear button secondary top-line">
<%= link_to 'Read more', index_path %></h5>
<h2>New Article</h2>
</div>
<div class="grid-x grid-padding-x small-up-2 medium-up-3 large-up-3">
<%= render 'arts/card' %>
</div>

<div class="cell small-title">
<h5 class="readmore clear button secondary top-line">
<%= link_to 'Read more', column_path %></h5>
<h2>New Column</h2>
</div>
<div class="grid-x grid-padding-x small-up-2 medium-up-3 large-up-3">
<%= render 'memos/me' %>
</div>

<div class="cell small-title">
<h2>Map</h2>
<%= render 'arts/maps' %>
</div>

<%= link_to 'Login with Facebook', auth_at_provider_path(provider: :facebook) %>
</div>

<div class="cell medium-3 large-3">
<%= render 'layouts/side' %>
</div>
</div>
</div>
</div>