config/routes.rb
Rails.application.routes.draw do
 
  resources :memos
  resources :arts do 
    resources :favorites, only: [:create, :destroy]
  end
  resources :user_sessions
  resources :users
  
  root 'static_pages#home'
  resources :sitemaps, :only => :index
  get 'sitemap.xml', to: 'sitemaps#index', :format => "xml", :as => :sitemap
  get  'about',  to: 'static_pages#about'
  get  '/help',  to: 'static_pages#help'
  get  'column',  to: 'static_pages#column'

  get 'static_pages/new'
  get  'static_pages/index'
  post 'static_pages/index'

  get  'login'  => 'user_sessions#new',     :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  
  get 'memo',  to: 'memos#index'
  get 'index',  to: 'arts#index'
  get 'new', 	  to: 'arts#new'
  get 'tags/:tag', to: 'arts#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	authenticates_with_sorcery! do |config|
        config.authentications_class = Authentication
    end

     # いいね機能のアソシエーション
    has_many :favorites, dependent: :destroy
    has_many :arts, through: :favorites
    has_many :authentications, :dependent => :destroy
    accepts_nested_attributes_for :authentications
	validates :password, length: {minimum: 6}
	validates :password, confirmation: true
 	validates :password_confirmation, presence: true
    validates :email, presence: true, uniqueness: true
    
    enum role: {
    	member: 1,
    	author: 2,
    	admin: 3
    }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, authetications_attributes: [:user_id, :provider, :uid, :_destroy])
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

   <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% set_meta_tags title: 'Edit', description: 'ユーザーのお気に入り' %>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<div id="login">
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% set_meta_tags title: 'お気に入り記事', description: 'ユーザーのお気に入り' %>
<p id="notice"><%= notice %></p>

<h3 class="side-title">お気に入り記事一覧</h3> 

<div class="grid-x grid-padding-x small-up-2 medium-up-3 large-up-3">
<% @user.arts.each do |art| %>
<div class="cell">
<div class="card">
  <%= image_tag art.mimages[0].url %>
  <div class="card-section">
  <%= link_to art_path(art) do %>
  <h4><%= art.storename %></h4>
  <% end %>
  <p class="cat-name cat-CULTURE"><%= art.area %></p>
  <p class="cat-name cat-CULTURE"><%= art.created_at.strftime("%Y年%m月%d日") %>
  </p>
  </div>
  </div>
  </div>
  <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>