config/routes.rb
Rails.application.routes.draw do
 
  resources :memos
  resources :arts do 
    resources :favorites, only: [:create, :destroy]
  end
  resources :user_sessions
  resources :users
  
  root 'static_pages#home'
  resources :sitemaps, :only => :index
  get 'sitemap.xml', to: 'sitemaps#index', :format => "xml", :as => :sitemap
  get  'about',  to: 'static_pages#about'
  get  '/help',  to: 'static_pages#help'
  get  'column',  to: 'static_pages#column'

  get 'static_pages/new'
  get  'static_pages/index'
  post 'static_pages/index'

  get  'login'  => 'user_sessions#new',     :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  
  get 'memo',  to: 'memos#index'
  get 'index',  to: 'arts#index'
  get 'new', 	  to: 'arts#new'
  get 'tags/:tag', to: 'arts#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/memo.rb
class Memo < ApplicationRecord
 mount_uploader :images, ImageUploader
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login,only: [:show, :index]
  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
    @tags = Art.tag_counts_on(:tags).order('count DESC')
    @beans = Art.tag_counts_on(:coffeebeans).order('count DESC')
    @arr = Art.pluck(:address)
    @ars = Art.pluck(:storename)
    if params[:tag]
    @art = Art.tagged_with(params[:tag])
    @art = Art.tagged_with(params[:coffeebean])
  else
    @memos = Memo.all
  end
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: 'Memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:title, :content,:shortcontent,:images)
    end
end

app/views/memos/_bigimg.html.erb
<div class="row expanded collapse">
  <div class="column">
    <div class="large-article-header" style="background-image:url(<%= @memo.images.url %>);">
      <div class="large-article-header-content">
        <div class="center-container">
          <div class="bigimg">
            <h1><%= @memo.title %></h1>
          </div>
          <div class="article-details">
          <div style="color:white; position: center;">
            <p><%= @memo.created_at.strftime("%Y年%m月%d日") %></p>
      	    </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/memos/_form.html.erb
<script async src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script async src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js'></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/github.min.css">
<script async src="https://sdk.amazonaws.com/js/aws-sdk-2.355.0.min.js"></script>

<%= form_for @memo do |f| %>
      <%= f.label :タイトル %>
      <%= f.text_field :title %>
      <%= f.label :ショートコンテンツ %>
      <%= f.text_field :shortcontent %>
      <%= f.label :写真 %>
      <%= f.file_field :images %>
    <label for="upload-file">
      <input type="file" id="upload-file">
    </label>
    <div class="grid-x" id='editor'>
      <textarea name="memo[content]" id="markdown" class="textarea text-left cell large-6 form-control" style="resize: none;" rows="20" v-model='input' debounce='50'></textarea>
      <div class="text-left cell large-6 preview border p-0">
        <div v-html='input | marked' id="marked-preview"></div>
      </div>
    </div>
    <div class="text-right">
      <%= f.submit "投稿する", :class => "btn btn-info" %>
    </div>
  <% end %>

<script>
  $(window).on('load', function() {
    var renderer = new marked.Renderer()
    renderer.code = function(code, language) {
      return '<pre'+'><code class="hljs">' + hljs.highlightAuto(code).value + '</code></pre>';
    };

    marked.setOptions({
      renderer: renderer,
      langPrefix: '',
      breaks : true
    });
    new Vue({
      el: '#editor',
      data: {
        input: '<%== j @memo.content %>',
      },
      filters: {
        marked: marked,
      },
    });
  });
$(function() {
  $("#upload-file").on('change', function() {
    var file = $("#upload-file").prop("files")[0];
    var timestamp = new Date().getTime();
    var filename = file.name.split('.')[0] + timestamp + ".jpg";
    var aaa = document.getElementById('upload-file');

    s3_client().putObject({Bucket: "markdown-coffee", Key: filename, ContentType: file.type, Body: file, ACL: 'public-read-write'},
    function(err, data){
      if(data !== null){
        // 画像表示
        var textarea = $('#markdown');
        var sentence = textarea.val();
        var word = `<img src=https://s3-ap-southeast-1.amazonaws.com/markdown-coffee/${filename}>`;

        // 画像のURLは、自分で決めた region, Bucket Name によって変わります。適宜書き換えてください
        // var src = aaa.src;
        sentence = sentence + '\n' + word;
        textarea.val(sentence);
        $("#marked-preview").html(marked(sentence))
         alert("アップロード成功");
      } else {
        alert("アップロード失敗かもしれない");
      }
    });
  });
  function s3_client() {
     // 自分の設定した region に書き換えてください。ここでは東京の region を指定しています
     AWS.config.region = 'ap-southeast-1'; // リージョン
     AWS.config.credentials = new AWS.CognitoIdentityCredentials({IdentityPoolId: 'ap-southeast-1:1588d149-0cd2-4470-a2eb-433f776e58e6'});
     AWS.config.credentials.get(function(err) {
        if (!err) {
            console.log("Cognito Identify Id: " + AWS.config.credentials.identityId);
        }
    });
     return new AWS.S3();
  };  
});
</script>

app/views/memos/_me.html.erb
<% @memos.each do |memo| %>
<div class="media-object">
  <div class="media-object-section">
  <div class="thumbnail">
  <%= image_tag memo.images.url, :size => "200x200" %>
    </div>
     </div>
   <div class="media-object-section linktoart">
    <%= link_to memo_path(memo) do %>
    <h4><strong><%= memo.title %></strong></h4>
    <% end %>
    <p><%= memo.shortcontent %></p>
  </div>
</div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>
<%= link_to 'Destroy', @memo, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>COLUMN</h1>
<%= render 'me', memo: @memo %>

app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<% set_meta_tags title: @memo.title, description: @memo.shortcontent %>

<div class="cell"><%= render 'bigimg' %></div>
<p>
	<div class="text-left"><%= markdown(@memo.content) %></div>
</p>