config/routes.rb
Rails.application.routes.draw do
 
  resources :memos
  resources :arts do 
    resources :favorites, only: [:create, :destroy]
  end
  resources :user_sessions
  resources :users
  
  root 'static_pages#home'
  resources :sitemaps, :only => :index
  get 'sitemap.xml', to: 'sitemaps#index', :format => "xml", :as => :sitemap
  get  'about',  to: 'static_pages#about'
  get  '/help',  to: 'static_pages#help'
  get  'column',  to: 'static_pages#column'

  get 'static_pages/new'
  get  'static_pages/index'
  post 'static_pages/index'

  get  'login'  => 'user_sessions#new',     :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  
  get 'memo',  to: 'memos#index'
  get 'index',  to: 'arts#index'
  get 'new', 	  to: 'arts#new'
  get 'tags/:tag', to: 'arts#index', as: :tag

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="grid-x small-up-1 medium-up-3">
		<div class="cell">
			<h4>About</h4>
			<hr>
			<span>
			COFFEE SEEKERは世界中の美味しいコーヒー・カフェを紹介するメディアです。スペシャリティーコーヒーを提供するカフェを中心に紹介していきます！
			</span>			
		</div>

	<div class="cell">
		<h4>Site Map</h4>
		<hr>
	   <%= link_to 'HOME', root_path %>
       <%= link_to 'CAFE', index_path %>
       <%= link_to 'ABOUT', about_path %>
       <%= link_to 'COLUMN', column_path %>
	</div>

	<div class="cell">
		<h4>Social Media</h4>
		<hr>
		<a href="https://www.facebook.com/Coffee-Seeker-295989787773339/">Facebook</a>
		<a href="https://twitter.com/coffeeseeker1">Twitter</a>
		<a href="https://www.instagram.com/coffeeseeker3/">Instagram</a>
	</div>
	</div>
</footer>

app/views/layouts/_google.html.erb
<meta name="google-site-verification" content="P_5yZ2xxMu0mcHqSUI9_Pr1quR7gm-iKIPQJPpDttro" />
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

app/views/layouts/_googleart.html.erb
<!-- Coffeeseeker Article -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9496679897493996"
     data-ad-slot="8500321603"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/layouts/_navbar.html.erb
<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <span class="title-bar-title"><%= image_tag("coffeeseeker.png", :size => "30x30", :alt => "アイコン") %><%= link_to 'COFFEE SEEKER', root_path %></span>
</div>

<div class="top-bar" id="example-menu">


  <span class="top-bar-left menu-text logo hide-for-small-only"><%= image_tag("coffeeseeker.png", :size => "30x30", :alt => "アイコン") %><%= link_to 'COFFEE SEEKER', root_path %></span>

  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <li><%= link_to 'HOME', root_path %></li>
      <li><%= link_to 'CAFE', index_path %></li>
      <li><%= link_to 'ABOUT', about_path %></li>
      <li><%= link_to 'COLUMN', column_path %></li>
      <% if false %> 
      <li><%= link_to 'STORE', index_path %></li>
      <li><%= link_to 'CONTACT', index_path %></li>
      <% end %>
      <li>
      <%= link_to index_path do %>
      <i class="fi-torso"></i>
      <% end %>
      <% if current_user %>
      <ul class="menu">
        <li><%= link_to "Favorite", user_path(current_user.id) %></li>
        <li><%= link_to "Edit", edit_user_path(current_user.id) %></li>
        <li><%= link_to "Logout", :logout, method: :post %></li>
      </ul>
       <% else %>
       <ul class="menu">
        <li><%= link_to "Register", new_user_path %></li>
        <li><%= link_to "Login", :login %></li>
       </ul>
       <% end %>
      </li>
    </ul>
  </div>
  </div>

app/views/layouts/_side.html.erb
<% if false %> #コメントアウト
<h3 class="side-title">Ranking(PV数)</h3> 
  <% @ranks.each.with_index do |art, i| %>

<h6 class="text-left ranking-number">No.<%= "#{i+1}" %></h6>
<div class="ranking-block">
<div class="ranking-image float-left"><%= image_tag art.mimages[0].url %></div>
<div class="ranking-text">
  <p class="cat-name cat-CULTURE"><%= art.created_at.strftime("%Y/%m/%d") %></p>
<%= link_to art_path(art) do %>
  <h6 class="ranking-title"><%= art.storename %></h6>
  <% end %>
  <p class="cat-name cat-CULTURE"><%= art.area %></p>
<p class="cat-name cat-CULTURE">(<%= REDIS.zscore("arts/", "#{art.id}").floor %>PV)</p>
   <span id="like-of-<%= art.id %>">
  <%= render partial: 'favorites/favorite', locals: { art: art, favorites: @favorites } %></span>
</div>
 </div>
  <% end %>
  <% end %>

<div><p class="text-left page-top">Area</p></div>
 <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
            <div class="button small button-color1"><%= link_to tag.name, tag_path(:action => :tag, :tag => tag.name), :class => css_class %>
            <%= tag.count %></div>
            <% end %>
<div><p class="text-left page-top">Coffee</p></div>
<% tag_cloud(@beans, %w(css1 css2 css3 css4)) do |tag, css_class| %>
            <div class="button small alert"><%= link_to tag.name, tag_path(:action => :tag, :tag => tag.name), :class => css_class %>
            <%= tag.count %></div>
            <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application",'data-turbolinks-track' => "reload"  %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => "reload" %>
     <%= render 'layouts/google' %>
    <%= favicon_link_tag 'coffeeseeker.ico' %>
    <%= display_meta_tags(default_meta_tags) %>
  </head>
  <body>
  
    <span id="notice"><%= flash[:notice] %></span>
    <span id="alert"><%= flash[:alert] %></span>
  
  <div class="content">

  <%= render 'layouts/navbar' %>

  <div class="grid-container">
    <div class="grid-x grid-margin-x">
    <div class="cell">
    <%= breadcrumbs semantic: true,
                separator: " &rsaquo; " %>

    <%= yield %>
    </div>
    </div>
    </div>
</div>

  <%= render 'layouts/footer' %>

  </div>
  
  </body>
</html>